### ISSUE TITLE
Pihole - c fails to start correct

### ISSUE THREAD

**Issue by schorschfunke** [max72bra/pi-hole-server-archlinux-customization#1]
Hi in chronometer.sh you must change '/run/pihole-FTL.port' to '/run/pihole-ftl/pihole-FTL.port' too.
Without 'pihole - c' says FTL: inactive

**Comment by graysky2** [comment]
Even correcting this, I get no output for the last 4 lines.  @schorschfunke do you?
```
|¯¯¯(¯)_|¯|_  ___|¯|___        Core: v5.2.2.
| ¯_/¯|_| ' \/ _ \ / -_)        Web: (not installed)
|_| |_| |_||_\___/_\___|        FTL: v5.3.3.
 ——————————————————————————————————————————————————————————
  Hostname: pihole             (Arch  )
    Uptime: 2 days, 15:24:45                                                                                                    
 Task Load: 0.07 0.02 0.15     (Active: 1 of 33 tasks)
 CPU usage: 1%                 (4x 1.5 GHz @ 54c)
 RAM usage: 8%                 (Used: 151 MB of 2 GB)
 HDD usage: 10%                (Used: 5 GB of 57 GB)
  LAN addr: 10.0.3.200         (Gateway: 10.0.3.1)
   Pi-hole: Active             (Blocking: 0 sites)
 Ads Today: 0%                 (Total: 0 of 0)
Local Qrys: 0%                 (2 DNS servers)
   Blocked: FTL offline                                                                                                         
Top Advert:                                                                                                                     
Top Domain:                                                                                                                     
Top Client:                                                                                  
```

**Comment by schorschfunke** [comment]
I get output, but I uncomment this lines in pihole-FTL.conf too
## Out of documentation
LOGFILE=/run/log/pihole-ftl/pihole-FTL.log
PIDFILE=/run/pihole-ftl/pihole-FTL.pid
PORTFILE=/run/pihole-ftl/pihole-FTL.port
SOCKETFILE=/run/pihole-ftl/FTL.sock

Without I get some warnings in the FTL Log

**Comment by graysky2** [comment]
@schorschfunke - Thanks for pointing that out.  Uncommenting them for me also gives output.

@max72bra - In addition to the fix, perhaps change our defaults to uncommented?

**Comment by schorschfunke** [comment]
Maybe, I'm changing it because sometimes Pihole hangs and I want get some debug logs and found these warnings. The hangs should gone with pi-hole-FTL 5.3.4

My system is a RPI4 with archlinuxarm 64bit

**Comment by max72bra** [comment]
@schorschfunke thanks for reporting!
@graysky2 yes I think we should uncomment them
i'll release everything ASAP

**Comment by schorschfunke** [comment]
@max72bra thanks for your hard work!

**Comment by max72bra** [comment]
this led me to realize that in FTL config.c the paths were completely left to their fate. changed the defaults according to the archlinux models. thanks again for everyone's cooperation. everything online.
