### ISSUE TITLE
Undefined variable $temperaturelimit in /srv/http/pihole/admin/scripts/pi-hole/php/header.php:379 

### ISSUE THREAD

**Issue by ilpianista** [max72bra/pi-hole-server-archlinux-customization#2]
May you please apply https://github.com/pi-hole/AdminLTE/pull/2054?

**Comment by PVasileff** [comment]
Same here, when I go to Settings in admin page.

`PHP error (2): Undefined variable $temperaturelimit in /var/www/html/admin/scripts/pi-hole/php/header.php:379
`
